services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - TZ=Europe/Zurich
    volumes:
      - /srv/${TENANT}/${APP}/data/postgres:/var/lib/postgresql/data
    networks:
      - ${PROJECT_NAME:-stack}-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 20s

networks:
  ${PROJECT_NAME:-stack}-net: {}


